### ISSUE TITLE
The passage of time stops at Day (0), Noon (6000), Night (12000) and Midnight (18000) if the time speed rate is set to less than 1

### ISSUE THREAD

**Issue by Skround** [DuckyCrayfish/hourglass#35] opened 2022-03-29 08:48 UTC
The passage of time stops at Day (0), Noon (6000), Night (12000) and Midnight (18000) if the time speed rate is set to less than 1.
Every time the time of day in the game reaches day, noon, night, or midnight, the time stops. I experimented with the configuration settings and noticed that the time stop only happens if the time speed is less than 1.0.
In my configuration day speed = 0.1 and night speed = 2
At night the time does not stop because the speed of the night is > than 1.0.

**Comment by DuckyCrayfish** [comment] 2022-04-04 03:57
That is bizarre, as I did many tests with the time speed set below 1.0. I wonder what could be causing this.

Would you mind giving me your Minecraft, Forge, and Hourglass versions? That would make troubleshooting much quicker for me.

**Comment by DuckyCrayfish** [comment] 2022-04-04 04:12
I tested this on the most recent recent Forge and Hourglass version, and I cannot seem to replicate the issue.

**Comment by DuckyCrayfish** [comment] 2022-06-22 02:13
Unfortunately since I was unable to reproduce this bug, I am going to close the issue. If you are able to create a set of repeatable instructions to replicate this bug on a fresh installation, let me know and we can re-open the issue.

Thanks and sorry for the inconvenience.

**Closed by DuckyCrayfish** 2022-06-22 02:13 UTC
Labels: bug
